---
title: "ESM 244 App Data Exploration"
author: "Meghan Cook"
date: "2/26/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Load Data & Packages
```{r}

library(tidyverse)
library(readr)
library(RColorBrewer)

df <- read_csv("2016_pres.csv")

```

#histograms of support donations to each
```{r}

df_pro_hil <- df %>% 
  filter(can_nam == "Clinton") %>%
  filter(sup_opp == "Support")

hist(df_pro_hil$exp_amo)
  
df_pro_tru <- df %>% 
  filter(can_nam == "Trump") %>%
  filter(sup_opp == "Support")

hist(df_pro_tru$exp_amo)

```

```{r}

df_hil <- df %>% 
  filter(can_nam == "Clinton")

ggplot(data=df_hil, aes(x=spe_nam, y=exp_amo, color=sup_opp)) +
  geom_bar(stat='identity') +
  theme_minimal()

exp_sum <- df %>% 
  group_by(can_nam, sup_opp, spe_nam) %>% 
  summarise(sum_exp = sum(exp_amo))

ggplot(data=exp_sum, aes(x=spe_nam, y=sum_exp, fill=sup_opp)) +
  geom_bar(stat='identity') +
  theme_minimal()
```

```{r}

exp_hil_sup <- exp_sum %>% 
  filter(can_nam == "Clinton") %>% 
  filter(sup_opp == "Support") %>% 
  arrange(desc(sum_exp))

exp_hil_opp <- exp_sum %>% 
  filter(can_nam == "Clinton") %>% 
  filter(sup_opp == "Oppose") %>% 
  arrange(desc(sum_exp))

exp_tru_sup <- exp_sum %>% 
  filter(can_nam == "Trump") %>% 
  filter(sup_opp == "Support") %>% 
  arrange(desc(sum_exp))

exp_tru_opp <- exp_sum %>% 
  filter(can_nam == "Trump") %>% 
  filter(sup_opp == "Oppose") %>% 
  arrange(desc(sum_exp)) %>% 
  slice(1:10)

par(mfrow = c(2,2))
hist(exp_hil_sup$sum_exp)
hist(exp_hil_opp$sum_exp)
hist(exp_tru_sup$sum_exp)
hist(exp_tru_opp$sum_exp)
  
```

```{r}

hil_sup_t10 <- exp_hil_sup %>%
  slice(1:10)
  
hil_opp_t10 <- exp_hil_opp %>%
  slice(1:10)

tru_sup_t10 <- exp_tru_sup %>%
  slice(1:10)
  
tru_opp_t10 <- exp_tru_opp %>%
  slice(1:10)

ggplot(data=hil_sup_t10, aes(x=spe_nam, y=sum_exp, fill=spe_nam)) +
  geom_bar(stat='identity') +
  theme_classic() +
  ggtitle("10 Largest Donors in Support of Clinton") +
  xlab("Donor Name") +
  ylab("Total Amount Donated (USD)")
  
```

```{r}

con_df <- read_csv("2016_congr.csv")

contab_df <- con_df %>% 
  filter(can_off != "P") %>%
  filter(can_par_aff == "Dem" | can_par_aff == "Rep") %>% 
  group_by(spe_nam, can_par_aff, sup_opp) %>% 
  summarise(sum_exp = sum(exp_amo))

con_sum_test <- contab_df %>%
  filter(can_par_aff == "Rep") %>% 
  filter(sup_opp == "Support") %>%
  arrange(desc(sum_exp))

ggplot(data=con_sum_test, aes(x=spe_nam, y=sum_exp, fill=spe_nam)) +
       geom_bar(stat='identity') +
       theme(axis.text.x=element_blank()) +
       ggtitle("Top 10 Largest Donors") +
       xlab("Donor Name") +
       ylab("Total Amount Donated (USD)") +
       scale_fill_brewer(palette="Set3")
     
sen_donors <- con_df %>%
  filter(can_off == "S") %>%
  group_by(spe_nam) %>% 
  summarise(sum_exp = sum(exp_amo)) %>% 
  arrange(desc(sum_exp)) %>% 
  slice(1:10)

```

